services:
  jackett:
    container_name: jackett
    image: ghcr.io/TheLovinator1/jackett:master
    restart: unless-stopped
    ports:
      - "9117:9117"
    volumes:
      - data:/var/lib/jackett
volumes:
  data:
