services:
  jackett:
    container_name: jackett
    image: ghcr.io/thelovinator1/jackett:master
    # build: .
    restart: unless-stopped
    ports:
      - "9117:9117"
    volumes:
      - data:/var/lib/jackett
volumes:
  data:
