name: Update Jackett version
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Jackett version
        id: vars
        run: |
          echo ::set-output name=latest_version::$(curl --silent "https://api.github.com/repos/jackett/jackett/releases/latest" | jq -r .tag_name)
          echo ::set-output name=latest_body::$(curl --silent "https://api.github.com/repos/jackett/jackett/releases/latest" | jq -r .body)
      - name: Update Dockerfile
        run: sed -i "s/ARG pkgver=.*/ARG pkgver=${{ steps.vars.outputs.latest_version }}/g" Dockerfile
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.LOVIBOT_TOKEN }}
          push-to-fork: LoviBot/jackett
          committer: LoviBot <99759169+LoviBot@users.noreply.github.com>
          author: LoviBot <99759169+LoviBot@users.noreply.github.com>
          signoff: true
          commit-message: Update version to ${{ steps.vars.outputs.latest_version }}
          title: Update version to ${{ steps.vars.outputs.latest_version }}
          body: "Hello 🤖\nI found a new version: ${{ steps.vars.outputs.latest_version }}\n ${{ steps.vars.outputs.latest_body }}"
